### PR TITLE
[feat] adding typescript to the package

### PR DESCRIPTION
**Pull request by rohittiwari-dev**
Add : Typings for typecript support whithout changing original files
Test : Passes all 138 test cases with mocha

Note : only added spport for using this package in typescript if required changes can be done each changes has been in [filename].d.ts

### CODE REVIEW

**Comment by mikuso** [comment]
Thanks for the contribution.

I've been hesitant to add typescript support so far (for reasons [discussed in other threads](https://github.com/mikuso/ocpp-rpc/pull/17#issuecomment-1780768076)), but I think I'd be happy to merge this since it doesn't try to solve the tricky problem of type safety with OCPP-specific calls.

Would you have time to label the private class members first? Any property or method beginning with a `_` ought to be labelled as private. If you don't have time, let me know and I'll find time to do it at some point.

Thanks again.

**Comment by rohittiwari-dev** [comment]
thanks for the consideration, i will push the update today itself after adding private access identifier to all data-members which starts with _

**Comment by rohittiwari-dev** [comment]
Hi @mikuso, I have added labeling of access identifiers to all class member starts with '_' as required either private or protected as needed the server passes all tests with mocha. Please consider merging this.

Thanks once again, and thanks to Sunday national holiday in 'India' for the time.

**Comment by mikuso** [comment]
Thanks for the contribution. Version 2.1.0 now published in npm.

**Pull request merged**
